### ISSUE TITLE
Sugerencia de Refactoring

### ISSUE THREAD

**Issue by emicordero** [aloussase/proyecto_poo_2020_2s2p#1]
¡Hola!, en mi curso de Diseño de Software estamos analizando repositorios e identificando si existen "bad smells" dentro de ellos. En la clase ControladorLotería.java hemos encontrado el bad smell "Message Chains". 
Adjunto un pequeño reporte sobre algunas técnicas de refactorización que se podrían aplicar a su código para un mejor entendimiento y funcionalidad.

[Repositorio#1_BadSmell.pdf](https://github.com/aloussase/proyecto_poo_2020_2s2p/files/6949935/Repositorio.1_BadSmell.pdf)

**Comment by aloussase** [comment]
Que eres loca, cuidado con estarme corrigiendo
